/**
 * Sprint 7.8: QA Data Scenarios (seeders)
 * Provides deterministic seed functions for QA testing scenarios
 */

import { resetMockDb, upsertUserById, getMockUserIdByRole, upsertRegistryPlot } from "@/lib/mockDb";
import { listAppeals } from "@/lib/appeals.store";
import { getPlots } from "@/lib/plots";
import type { AppealStatus, AppealCategory } from "@/lib/office/types";

type SeedScope = "all" | "users" | "plots" | "appeals" | "templates";

export type SeedCounts = {
  users: number;
  plots: number;
  appeals: number;
  templates: number;
};

/**
 * Deterministic user IDs for scenarios
 */
const SCENARIO_USER_IDS = {
  resident1: "qa-seed-resident-1",
  resident2: "qa-seed-resident-2",
  resident3: "qa-seed-resident-3",
  debtor1: "qa-seed-debtor-1",
  debtor2: "qa-seed-debtor-2",
  noContact: "qa-seed-no-contact-1",
  noPlot: "qa-seed-no-plot-1",
} as const;

/**
 * Deterministic appeal IDs for scenarios
 */
// Note: Appeal IDs are generated by createAppeal, so we don't use deterministic IDs
// The scenarios structure ensures consistent data patterns for QA testing

const now = new Date();
const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);
const twoDaysAgo = new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000);
const tomorrow = new Date(now.getTime() + 24 * 60 * 60 * 1000);

/**
 * Create seed appeal using createAppeal and update fields
 */
async function createSeedAppeal(params: {
  userId: string;
  title: string;
  body: string;
  category?: AppealCategory;
  status?: AppealStatus;
  assigneeRole?: "chairman" | "secretary" | "accountant" | "admin";
  dueAt?: string;
  plotNumber?: string;
  authorName?: string;
  authorPhone?: string;
  priority?: "low" | "medium" | "high";
}): Promise<string | null> {
  try {
    const { createAppeal } = await import("@/lib/appeals.store");
    const appeal = await createAppeal({
      title: params.title,
      body: params.body,
      authorId: params.userId,
      authorName: params.authorName,
      authorPhone: params.authorPhone,
      plotNumber: params.plotNumber,
      dueAt: params.dueAt,
    });
    
    if (appeal) {
      // Update fields that createAppeal doesn't accept
      const { updateAppealStatus, updateAppealPriority } = await import("@/lib/appeals.store");
      if (params.status && params.status !== appeal.status) {
        await updateAppealStatus(appeal.id, params.status, "admin");
      }
      if (params.priority && params.priority !== appeal.priority) {
        await updateAppealPriority(appeal.id, params.priority);
      }
      if (params.assigneeRole && params.assigneeRole !== appeal.assigneeRole) {
        const { assignToRole } = await import("@/server/services/appeals");
        await assignToRole(appeal.id, params.assigneeRole);
      }
      return appeal.id;
    }
    return null;
  } catch (error) {
    console.error("[seedScenarios] Failed to create appeal:", error);
    return null;
  }
}

/**
 * seedClean: Reset to minimal clean state
 */
export async function seedClean(scope: SeedScope = "all"): Promise<SeedCounts> {
  if (scope === "all") {
    resetMockDb();
  }

  // Ensure basic users exist
  if (scope === "all" || scope === "users") {
    upsertUserById({ id: "user-admin-root", role: "admin", fullName: "Администратор СНТ", email: "admin@snt.ru" });
    upsertUserById({ id: "user-resident-default", role: "resident", fullName: "Житель Тестовый" });
  }

  const appeals = scope === "all" || scope === "appeals" ? [] : listAppeals();
  const plots = scope === "all" || scope === "plots" ? [] : await getPlots();

  return {
    users: scope === "all" || scope === "users" ? 2 : 0,
    plots: plots.length,
    appeals: appeals.length,
    templates: 0,
  };
}

/**
 * seedDemo: Demo data with variety
 */
export async function seedDemo(scope: SeedScope = "all"): Promise<SeedCounts> {
  if (scope === "all") {
    resetMockDb();
  }

  const counts: SeedCounts = { users: 0, plots: 0, appeals: 0, templates: 0 };

  // Users
  if (scope === "all" || scope === "users") {
    upsertUserById({ id: "user-admin-root", role: "admin", fullName: "Администратор СНТ", email: "admin@snt.ru" });
    upsertUserById({ id: "user-resident-default", role: "resident", fullName: "Житель Тестовый" });
    upsertUserById({ id: SCENARIO_USER_IDS.resident1, role: "resident", fullName: "Иван Петров", phone: "+7 900 111-11-11" });
    upsertUserById({ id: SCENARIO_USER_IDS.resident2, role: "resident", fullName: "Мария Сидорова", phone: "+7 900 222-22-22" });
    counts.users = 4;
  }

  // Plots
  if (scope === "all" || scope === "plots") {
    upsertRegistryPlot({ plotDisplay: "Улица Центральная, участок 1", cadastral: "74:00:0000000:1201", seedOwnerName: "Иван Петров", seedOwnerPhone: "+7 900 111-11-11" });
    upsertRegistryPlot({ plotDisplay: "Улица Центральная, участок 2", cadastral: "74:00:0000000:1202", seedOwnerName: "Мария Сидорова", seedOwnerPhone: "+7 900 222-22-22" });
    counts.plots = 2;
  }

  // Appeals
  if (scope === "all" || scope === "appeals") {
    const appealId = await createSeedAppeal({
      userId: SCENARIO_USER_IDS.resident1,
      title: "Демо-обращение 1",
      body: "Пример обращения для демонстрации",
      category: "general",
      status: "new",
    });
    if (appealId) counts.appeals = 1;
  }

  return counts;
}

/**
 * seedDebtor: Users with debts
 */
export async function seedDebtor(scope: SeedScope = "all"): Promise<SeedCounts> {
  if (scope === "all") {
    resetMockDb();
  }

  const counts: SeedCounts = { users: 0, plots: 0, appeals: 0, templates: 0 };

  // Users with debt flags (actual debt would be in finance store)
  if (scope === "all" || scope === "users") {
    upsertUserById({ id: SCENARIO_USER_IDS.debtor1, role: "resident", fullName: "Должник 1", phone: "+7 900 300-11-11" });
    upsertUserById({ id: SCENARIO_USER_IDS.debtor2, role: "resident", fullName: "Должник 2", phone: "+7 900 300-22-22" });
    counts.users = 2;
  }

  // Appeals related to debt
  if (scope === "all" || scope === "appeals") {
    const appealId = await createSeedAppeal({
      userId: SCENARIO_USER_IDS.debtor1,
      title: "Вопрос о задолженности",
      body: "Хочу уточнить сумму задолженности",
      category: "finance",
      status: "new",
    });
    if (appealId) counts.appeals = 1;
  }

  return counts;
}

/**
 * seedOverdue: Appeals with dueAt in past
 */
export async function seedOverdue(scope: SeedScope = "all"): Promise<SeedCounts> {
  if (scope === "all") {
    resetMockDb();
  }

  const counts: SeedCounts = { users: 0, plots: 0, appeals: 0, templates: 0 };

  // Users
  if (scope === "all" || scope === "users") {
    upsertUserById({ id: SCENARIO_USER_IDS.resident1, role: "resident", fullName: "Иван Петров", phone: "+7 900 111-11-11" });
    counts.users = 1;
  }

  // Appeals with overdue dates
  if (scope === "all" || scope === "appeals") {
    const ids = await Promise.all([
      createSeedAppeal({
        userId: SCENARIO_USER_IDS.resident1,
        title: "Просроченное обращение 1",
        body: "Это обращение просрочено",
        category: "access",
        status: "in_progress",
        assigneeRole: "secretary",
        dueAt: twoDaysAgo.toISOString(),
        priority: "high",
      }),
      createSeedAppeal({
        userId: SCENARIO_USER_IDS.resident1,
        title: "Просроченное обращение 2",
        body: "Еще одно просроченное обращение",
        category: "electricity",
        status: "in_progress",
        assigneeRole: "accountant",
        dueAt: yesterday.toISOString(),
        priority: "high",
      }),
      createSeedAppeal({
        userId: SCENARIO_USER_IDS.resident1,
        title: "Скоро срок обращения",
        body: "Срок истекает завтра",
        category: "finance",
        status: "in_progress",
        assigneeRole: "chairman",
        dueAt: tomorrow.toISOString(),
        priority: "medium",
      }),
    ]);
    counts.appeals = ids.filter(Boolean).length;
  }

  return counts;
}

/**
 * seedNoContact: Appeals without contact info
 */
export async function seedNoContact(scope: SeedScope = "all"): Promise<SeedCounts> {
  if (scope === "all") {
    resetMockDb();
  }

  const counts: SeedCounts = { users: 0, plots: 0, appeals: 0, templates: 0 };

  // Users without contact
  if (scope === "all" || scope === "users") {
    upsertUserById({ id: SCENARIO_USER_IDS.noContact, role: "resident", fullName: "Без контакта", phone: undefined, email: undefined });
    counts.users = 1;
  }

  // Appeals without contact
  if (scope === "all" || scope === "appeals") {
    const appealId = await createSeedAppeal({
      userId: SCENARIO_USER_IDS.noContact,
      title: "Обращение без контакта",
      body: "Нет телефона и email",
      category: "general",
      status: "new",
      authorName: undefined,
      authorPhone: undefined,
    });
    if (appealId) counts.appeals = 1;
  }

  return counts;
}

/**
 * seedNoPlot: Appeals without plot number
 */
export async function seedNoPlot(scope: SeedScope = "all"): Promise<SeedCounts> {
  if (scope === "all") {
    resetMockDb();
  }

  const counts: SeedCounts = { users: 0, plots: 0, appeals: 0, templates: 0 };

  // Users
  if (scope === "all" || scope === "users") {
    upsertUserById({ id: SCENARIO_USER_IDS.noPlot, role: "resident", fullName: "Без участка", phone: "+7 900 400-11-11" });
    counts.users = 1;
  }

  // Appeals without plot
  if (scope === "all" || scope === "appeals") {
    const appealId = await createSeedAppeal({
      userId: SCENARIO_USER_IDS.noPlot,
      title: "Обращение без участка",
      body: "Не указан номер участка",
      category: "general",
      status: "new",
      plotNumber: undefined,
    });
    if (appealId) counts.appeals = 1;
  }

  return counts;
}

/**
 * seedMixed: Combination of various scenarios
 */
export async function seedMixed(scope: SeedScope = "all"): Promise<SeedCounts> {
  if (scope === "all") {
    resetMockDb();
  }

  const counts: SeedCounts = { users: 0, plots: 0, appeals: 0, templates: 0 };

  // Mix of users
  if (scope === "all" || scope === "users") {
    upsertUserById({ id: SCENARIO_USER_IDS.resident1, role: "resident", fullName: "Иван Петров", phone: "+7 900 111-11-11" });
    upsertUserById({ id: SCENARIO_USER_IDS.debtor1, role: "resident", fullName: "Должник 1", phone: "+7 900 300-11-11" });
    upsertUserById({ id: SCENARIO_USER_IDS.noContact, role: "resident", fullName: "Без контакта", phone: undefined });
    counts.users = 3;
  }

  // Mix of appeals
  if (scope === "all" || scope === "appeals") {
    const ids = await Promise.all([
      createSeedAppeal({
        userId: SCENARIO_USER_IDS.resident1,
        title: "Нормальное обращение",
        body: "Полностью заполненное обращение",
        category: "general",
        status: "new",
      }),
      createSeedAppeal({
        userId: SCENARIO_USER_IDS.debtor1,
        title: "Обращение должника",
        body: "Про долги",
        category: "finance",
        status: "in_progress",
        assigneeRole: "accountant",
        dueAt: yesterday.toISOString(),
      }),
      createSeedAppeal({
        userId: SCENARIO_USER_IDS.noContact,
        title: "Без контакта",
        body: "Нет контактной информации",
        category: "general",
        status: "new",
        authorPhone: undefined,
      }),
    ]);
    counts.appeals = ids.filter(Boolean).length;
  }

  return counts;
}

/**
 * Main seed function dispatcher
 */
export async function seedScenario(
  scenario: "clean" | "demo" | "debtor" | "overdue" | "noContact" | "noPlot" | "mixed",
  scope: SeedScope = "all"
): Promise<SeedCounts> {
  switch (scenario) {
    case "clean":
      return seedClean(scope);
    case "demo":
      return seedDemo(scope);
    case "debtor":
      return seedDebtor(scope);
    case "overdue":
      return seedOverdue(scope);
    case "noContact":
      return seedNoContact(scope);
    case "noPlot":
      return seedNoPlot(scope);
    case "mixed":
      return seedMixed(scope);
    default:
      throw new Error(`Unknown scenario: ${scenario}`);
  }
}
