#!/usr/bin/env node

import { execSync } from "child_process";
import { writeFileSync, mkdirSync, existsSync, readFileSync } from "fs";
import { join } from "path";
import { fileURLToPath } from "url";
import { dirname } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, "..");

// Get git commit hash
let commitHash = "unknown";
try {
  commitHash = execSync("git rev-parse --short HEAD", { cwd: projectRoot, encoding: "utf-8" }).trim();
} catch (error) {
  console.warn("Warning: Could not get git commit hash:", error.message);
}

// Generate timestamp slug (YYYY-MM-DD_HH-mm)
const now = new Date();
const year = now.getFullYear();
const month = String(now.getMonth() + 1).padStart(2, "0");
const day = String(now.getDate()).padStart(2, "0");
const hours = String(now.getHours()).padStart(2, "0");
const minutes = String(now.getMinutes()).padStart(2, "0");
const slug = `${year}-${month}-${day}_${hours}-${minutes}`;

// Create output directories
const runsDir = join(projectRoot, "docs", "qa", "runs");
const assetsDir = join(runsDir, `${slug}_assets`);

if (!existsSync(runsDir)) {
  mkdirSync(runsDir, { recursive: true });
}
if (!existsSync(assetsDir)) {
  mkdirSync(assetsDir, { recursive: true });
}

// Get baseURL
const baseURL = process.env.PLAYWRIGHT_BASE_URL || "http://localhost:3000";

console.log(`Running QA report test...`);
console.log(`Commit: ${commitHash}`);
console.log(`Base URL: ${baseURL}`);
console.log(`Output: ${assetsDir}`);

// Run Playwright test
let testExitCode = 1;
let testOutput = "";
try {
  testOutput = execSync(
    `npx playwright test tests/qa-report/admin-qa-report.spec.ts --reporter=line`,
    {
      cwd: projectRoot,
      encoding: "utf-8",
      env: {
        ...process.env,
        REPORT_OUT_DIR: assetsDir,
        PLAYWRIGHT_BASE_URL: baseURL,
      },
      stdio: "pipe",
    }
  );
  testExitCode = 0;
} catch (error) {
  testOutput = error.stdout || error.message;
  testExitCode = error.status || 1;
}

// Read test results if available
let steps = [];
let roleChecks = [];
const resultsPath = join(assetsDir, "results.json");
if (existsSync(resultsPath)) {
  try {
    const results = JSON.parse(readFileSync(resultsPath, "utf-8"));
    steps = results.steps || [];
    roleChecks = results.roleChecks || [];
  } catch (error) {
    console.warn("Warning: Could not read results.json:", error.message);
  }
}

// Determine final status
const finalStatus = testExitCode === 0 ? "PASS" : "FAIL";

// Generate markdown report
const reportPath = join(runsDir, `${slug}.md`);
const reportDate = now.toISOString().replace("T", " ").substring(0, 19);

let markdown = `# QA Report: Admin QA Tools

**Date:** ${reportDate}  
**Commit hash:** \`${commitHash}\`  
**Base URL:** ${baseURL}  
**Status:** ${finalStatus === "PASS" ? "✅ PASS" : "❌ FAIL"}

---

## Test Steps

`;

// Add steps
if (steps.length > 0) {
  for (const step of steps) {
    const statusIcon = step.status === "pass" ? "✅" : "❌";
    markdown += `### ${statusIcon} ${step.step}\n\n`;
    if (step.screenshot) {
      const relativePath = `${slug}_assets/${step.screenshot}`;
      markdown += `![${step.step}](${relativePath})\n\n`;
    }
    if (step.notes) {
      markdown += `**Notes:** ${step.notes}\n\n`;
    }
  }
} else {
  markdown += `No steps recorded.\n\n`;
}

// Add role checks
if (roleChecks.length > 0) {
  markdown += `## Role Checks\n\n`;
  for (const check of roleChecks) {
    const statusIcon = check.found ? "✅" : "⚠️";
    markdown += `- ${statusIcon} **${check.page}** - ${check.check}`;
    if (check.found && check.text) {
      markdown += `: "${check.text}"`;
    }
    markdown += `\n`;
  }
  markdown += `\n`;
}

// Add screenshots list
const screenshots = steps.filter((s) => s.screenshot).map((s) => s.screenshot);
if (screenshots.length > 0) {
  markdown += `## Screenshots\n\n`;
  for (const screenshot of screenshots) {
    const relativePath = `${slug}_assets/${screenshot}`;
    markdown += `- [${screenshot}](${relativePath})\n`;
  }
  markdown += `\n`;
}

// Add test output if failed
if (testExitCode !== 0) {
  markdown += `## Test Output\n\n\`\`\`\n${testOutput}\n\`\`\`\n\n`;
}

markdown += `---\n\n*Generated by \`npm run qa:report\`*\n`;

// Write report
writeFileSync(reportPath, markdown, "utf-8");

console.log(`\n✅ Report generated: ${reportPath}`);
console.log(`📁 Assets directory: ${assetsDir}`);
console.log(`\nStatus: ${finalStatus}`);

// Exit with test exit code
process.exit(testExitCode);
